### PR TITLE
Refactored the useChatStream Hook to improve readability and maintainability

### PR DESCRIPTION
**Pull request by MatchuPitchu**
I used your hook as a basis in my own project. Thanks for this. I would like to share with you some of my refactored code to improve the code readability and simplify some of the functions. The new code still maintains the original functionality but includes types (instead of interfaces). I didn't want to change your return style. My preference would always be to return an object. With an array you can use `as const` in TypeScript. Please note I've added two functions to your array that I think are useful.

I replaced some of your enums, because I prefer auto-completion for union types, which means that users can simply work with strings.

In my own project, I immediately replaced the entire SSE package because it was written with old syntax and, in my opinion, is difficult to understand. I implemented this in TypeScript myself, but it's not included here in this pull request because then all your tests with the mocking of the SSE failed. If you are interested, let me know.

### CODE REVIEW

**Comment by yoDon** [comment]
Hi @MatchuPitchu and/or @jonrhall - can I suggest two thoughts on this PR?

(1) How do you feel about changing the proposed `resetMessages()` into a `setMessages(value: ChatMessage[])`? `setMessages()` would be more general in that it can be used to modify/rewrite the conversation history in addition to being usable as a reset function if you just pass `[]` as the function argument. Like MatchuPitchu's experience, this was one of the first things I stubbed into a local fork while playing with it, to make it easier for me to iterate on conversations while exploring prompts.

(2) It would be great to be able to pass the `temperature` parameter into the hook constructor. While messing around unsuccessfully with some prompt ideas, I eventually realized I needed to reduce the temperature to get them to work properly, which at present isn't possible with this hook.

I don't think either of these involves more than a tiny amount of code. Happy to help implement if that's useful, or stay out of the way if it's easier for one of you to do it.

**Comment by MatchuPitchu** [comment]
Thank you for your thoughts, @yoDon . I adapted my own version in my private project, so of course I'll leave all the decisions to @jonrhall here.

1) I'm a fan of separation of concerns, so I think my solution with an explicit reset function is better. This resets the setMessages internally in the hook.

2) Yes, I think this would be nice. In general, all options available according to the OpenAI Documentation should be adjustable.

**Comment by MatchuPitchu** [comment]
> Hi @MatchuPitchu and/or @jonrhall - can I suggest two thoughts on this PR?
> 
> (1) How do you feel about changing the proposed `resetMessages()` into a `setMessages(value: ChatMessage[])`? `setMessages()` would be more general in that it can be used to modify/rewrite the conversation history in addition to being usable as a reset function if you just pass `[]` as the function argument. Like MatchuPitchu's experience, this was one of the first things I stubbed into a local fork while playing with it, to make it easier for me to iterate on conversations while exploring prompts.
> 
> (2) It would be great to be able to pass the `temperature` parameter into the hook constructor. While messing around unsuccessfully with some prompt ideas, I eventually realized I needed to reduce the temperature to get them to work properly, which at present isn't possible with this hook.
> 
> I don't think either of these involves more than a tiny amount of code. Happy to help implement if that's useful, or stay out of the way if it's easier for one of you to do it.

**Comment by jonrhall** [comment]
@MatchuPitchu Thanks for putting forward this PR, I'm looking at incorporating your and @yoDon's feedback into my next set of changes. A couple of thoughts so far as I work through your the comments here:

1. I definitely understand the need for a `setMessages` and `resetMessages` function(s). I'm still thinking through the implementation of this, I think having them be one `setMessages` function instead of two is probably the way I'm going to head, but this is still TBD. I was trying to avoid having this hook do too much in the way of its return value because I really like the simplicity of a React Hook returning a tuple `[value, setValue]` instead of an object--it's a very well-understood pattern that everyone is already familiar with, but I think we're at the limits of its usefulness. What's important to think about here is, when a `setMessages` function is invoked, how the hook knows it needs to call the API and how sometimes you're just looking for it to update the current list of messages in its state without sending an API request.
2. It's clear I need to add a Prettier definition for this project. There are some things in your PR that are regressions from the style I like to use, but that's not being enforced as strictly as I thought via ESLint, and Prettier is the right solution here IMO to make sure that we're all on the same page.
3. I don't quite understand the need for changing the interfaces to types, can you explain that to me?
4. What was the reason for needing to expose a `closeStream` function in the hook? Is that so you can tell it to stop generating a response mid-stream? I hadn't thought of this, and it's a really good idea if that's what you're using it for, I'd want to add that in my update as well.
5. The next set of changes will much more closely mirror the options available when creating the openai client directly--i.e. support for `temperature` and any related settings will be coming in the next change. I totally understand the need for this.
6. Enums are a best practice--magic strings are an anti-pattern. They also have a very nice side-benefit of a more strictly-typed interface with this hook library, where it can proactively express the versions of GPT that are supported only after they have been tested and verified to work (and this also allows for nice source control tracking of support for various versions).
7. There was a reason that I didn't want to touch the SSE package, and that was because I didn't want this project to own its implementation, for proper separation of concerns. I'm not an expert on ReadableStreams and there's implementation details in that code that I haven't fully grok'd (nor do I want to b/c it doesn't relate to this project), which is why I only provided a basic interface for the parts of the SSE module that I used in the project's type definitions. I would love a PR for updating the SSE dependency of this repo, if you wanted to publish your SSE implementation as its own project? It would be great to get full native TS support with that SSE dependency, I just don't think this project is the place for that to live.

**Comment by jonrhall** [comment]
@MatchuPitchu looking through [your most recent code ](https://github.com/MatchuPitchu/open-ai/blob/main/src/hooks/useOpenAIChatStream.ts) (not what was is recorded in this PR but the link in your most recent message) I'm really liking what you've done. I really like that you removed the SSE dependency entirely, that's really great. I also see that you kept the enums in which I think is important as well... all around great work! I'll be incorporating your changes in the main project shortly--thank you for the update.

**Comment by MatchuPitchu** [comment]
@jonrhall : Thank you, yes feel free to use my own hook. Gladly with a small reference to my Github repo or as a contributor to the package.json.

A few more thoughts on your above answer:

1. Yes, you are absolutely right and with 2 destructured values it also makes sense. But in your tests you can also see that array destructuring is not optimal in my opinion (see if you only need the second value).

2. Yes, I agree with you there too. Everyone has their habits and tastes. I personally use other patterns and ESLint rules.

3.  This is regularly a big discussion. I'm going by Matt Pocock's very cogent argument: https://www.youtube.com/watch?v=zM9UPcIyyhQ . In your case, the interfaces were also very useful. However, for the sake of clarity, I prefer intersection types to merge different types. I find Inheritance more confusing, but that too is a matter of taste.

4. Yes, exactly. As with ChatGPT in the original. Imagine you want a React Component written by the AI, but you made a mistake in your prompt. Then you save money and time if you can cancel immediately. I now have the abort function myself for this.

6. Here I actually have a completely different opinion. You overlooked it, but I only use string literal unions in my own custom hook. The advantage is that the consumer of the hook does not have to import an extra enum, but has 1) auto-completion in his IDE, which values he may use and 2) if he makes a typo, it is immediately marked in red and not accepted.

**Comment by jonrhall** [comment]
@MatchuPitchu @yoDon just published major changes to the hook, addressing all your feedback here.

@MatchuPitchu in particular, I think I improved on the way you were handling the streaming completion chunks, I used an async iterator which I think really helped to clean the code up.

I also moved the majority of the handling of the `fetch` request and the incoming chunks into a separate [openAiStreamingDataHandler](https://github.com/jonrhall/openai-streaming-hooks/blob/main/src/chat-stream-handler.ts#L37) function that does the majority of the work. The more I worked on these improvements the more this became an obvious abstraction to make, I hope you'll agree.

Unit tests have been added for all functionality (95%+ code coverage).

I would be curious for both of your feedback on the `openAiStreamingDataHandler`, in particular whether this is a useful abstraction that maybe should be its own GitHub project? But also, also feedback on the changes in general.

**Comment by MatchuPitchu** [comment]
Thank you for your message @jonrhall 

The readme is very well done. Thanks also for mentioning me.

About your code: We have different tastes in some things, but looks good.
You can delete the `ssm.d.ts` - you don't need it anymore. Otherwise, I always find code easier to read when early returns are used for `if statements`. So you avoid nesting.

Thanks for your work!

**Pull request closed without merging**
